insert into CUSTOMER_ACCOUNT ( ACCOUNT_VALUE,ACCOUNT_CURRENCY) VALUES (300,"RON");
insert into CUSTOMER_ACCOUNT ( ACCOUNT_VALUE,ACCOUNT_CURRENCY) VALUES (123,"RON");
insert into CUSTOMER_ACCOUNT ( ACCOUNT_VALUE,ACCOUNT_CURRENCY) VALUES (301240,"RON");
