CREATE TABLE
    `CUSTOMER_ACCOUNT` (

        `ACCOUNT_ID` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
        `ACCOUNT_NAME` int(11) DEFAULT 0,
        `ACCOUNT_VALUE` int(11) DEFAULT 0,
        `ACCOUNT_CURRENCY` varchar(5) DEFAULT NULL
) ENGINE = InnoDB DEFAULT CHARSET = latin1 COLLATE = latin1_swedish_ci
;

