apiVersion: apps/v1
kind: Deployment # what to create?
metadata:
  name: bankbk
spec: # specification for deployment resource
  replicas: 1 # how many replicas of pods we want to create
  selector:
    matchLabels:
      app: bankbk
  template: # blueprint for pods
    metadata:
      labels:
        app: bankbk # service will look for this label
    spec: # specification for pods
      containers: # we can have one or more containers
        - name: bankbk
          image: bankbk/latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080