CREATE TABLE
    `CUSTOMER_ACCOUNT` (
                           `ACCOUNT_ID` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
                           `ACCOUNT_VALUE` int(11) DEFAULT 0,
                           `ACCOUNT_CURRENCY` varchar(5) DEFAULT NULL
) ENGINE = InnoDB DEFAULT CHARSET = latin1 COLLATE = latin1_swedish_ci
ALTER TABLE CUSTOMER_ACCOUNT
    ADD PRIMARY KEY (ACCOUNT_ID);

    insert into CUSTOMER_ACCOUNT(ACCOUNT_ID, ACCOUNT_VALUE,ACCOUNT_CURRENCY) VALUES ("INGM123123",300,"RON");